version: 3

images:
  base_image:
    name: quay.io/ansible/ansible-runner:latest

dependencies:
  ansible_core:
    package_pip: ansible-core>=2.16,<2.17

  galaxy:
    collections:
      - name: ansible.posix
      - name: ansible.utils
      - name: ansible.netcommon

  python:
    - requests
    - jmespath

options:
  package_manager_path: /usr/bin/microdnf
